### PR TITLE
Viewset bug fix

### LINKED ISSUE #33: ViewSet actions on policy doesnot work properly
below is my policy.

from rest_access_policy import AccessPolicy

class SearchAccessPolicy(AccessPolicy):
    statements = [
        {
            "action": ["person"],
            "principal": ["authenticated"],
            "effect": "allow",
        }
    ]

and i also have a function in a ViewSet-based class.
 @action(methods=['POST'], detail=False, name='person')
    def person(self, request):
...
...
..

Even though i try to make a request as logged in user. it gives 403 error. How can i solve this problem?

### PR DESCRIPTION
**Pull request by oguzhancelikarslan**
closes #33 
action returns none sometimes but we can use action_map it returns the dict every time.

### CODE REVIEW

**Comment by oguzhancelikarslan** [comment]
Attached an image to show you the situation.
problem

**Comment by rsinger86** [comment]
Hi - thanks for looking into this. 

I'm not sure it's safe to assume that the first element of `action_map.values()` is correct? DRF viewsets have multiple mapped values (HTTP verb -> viewset method)? 

Under what circumstances is `action` = `None`?

**Comment by doconix** [comment]
I'm hitting this issue as well. I can give a little more detail.

When the `@action` decorator is used (e.g. not a normal viewset method), DRF sets the `view.action` to None. You can see this at https://github.com/encode/django-rest-framework/blob/master/rest_framework/viewsets.py#L145

With an @action, the method might be PUT, POST, or whatever.  DRF isn't mapping it right, and AFAIK, it won't ever map custom actions right.

I can't speak specifically to this PR as a solution (just haven't looked yet), but I can definitely say I'm hitting the same thing.

**Comment by rsinger86** [comment]
Is it possible this is due to your project using an older version of DRF?

**Comment by oguzhancelikarslan** [comment]
I use the latest version of DRF. I fixed my problem with my pull request.

**Comment by oguzhancelikarslan** [comment]
Getting same error still please merge this pull request or take a look at it.  I reviewed DRF code again. 
action_map does not store all actions defined on viewset.
action_map is equal to {'post', 'function name on viewset"}, let say we defined extend our generic view with CreateModelMixin in our case if we make a request action_map will be {'post', 'create'} so we can use 'create' here. To find appropriate policies.

self.action = self.action_map.get(method)

**Comment by rsinger86** [comment]
Thanks! This fix in in the new 0.8.0 release. I made a small tweak to return the view.action if it's not None and fallback on the action_map value.
https://github.com/rsinger86/drf-access-policy/blob/0244545b08d03d02773925e6f0937c09bd036167/rest_access_policy/access_policy.py#L44

**Pull request merged**
