### PR TITLE
Adds admin and staff to principals

### PR DESCRIPTION
**Pull request by BarnabasSzabolcs**
Awesome project with awesome documentation, @rsinger86 !
This is how permissions should look like!

I have added admin and staff to principal categories and updated the docs too because they simplify user access permissions a lot, even without using groups.

Best,
Barney

### CODE REVIEW

**Comment by BarnabasSzabolcs** [comment]
Hi @rsinger86 ,

I hope you don't mind that I added this feature to Your project. 

I like the structure of the project, it was very clear how to add to it.
I saw that there were many packages in requirements.txt that are not really used.
So, I used pip-tools to clean up requirements. Anytime you have a new package to depend on, 
you can just add it to requirements.in and run pip-compile && pip-sync I have added docs to requirements.in.
Also, I removed all the imports that are not used anymore. 
Later maybe it is nice to add some automatic test runner for pr-s that runs ./manage.py test.

Best,
Barney

**Comment by BarnabasSzabolcs** [comment]
@rsinger86 Hi Robert, can you please merge this change?
Thanks,
Barney

**Comment by rsinger86** [comment]
Yes, thank you! Sorry, I've been distracted. 

I've been meaning to learn more about packaging and dependencies best practices for Python. Any learning resources you'd recommend?

**Comment by BarnabasSzabolcs** [comment]
Thanks Robert, no worries. 

I don't know much about best practices for pip projects. What I use - and it serves me well - is this pip-tools.
https://github.com/jazzband/pip-tools

pip-tools takes care of my implied requirements and also keeps my versions stable.

I usually set up a requirements.in, only specifying the versions where I need an older package. (say, django==2.2.12 because my project is incompatible with django 3)

Then I run `pip-compile && pip-sync` . 

Note that pip-compile does not override versions already in the requirements.txt, so if you want to upgrade packages to the latest, delete them from requirements.txt first and then  run the command.
If you want to upgrade all the packages, delete requirements.txt before running the command.

Best,    
Barney

**Pull request merged**
