### PR TITLE
Allow to pass BasePermission subclass/instance as condition (resolve #3)

### LINKED ISSUE #3: Allow to pass BasePermission subclasses into `condition` statement
There is few default classes like `IsAuthorized` but there is no reason to create custom method:
```
def is_authorized(self, *args, **kwargs):
    return IsAuthorized.has_permission(*args, **kwargs)
```

Istead just add check of condition value (`isclass(cond) and issubclass(cond, BasePermission) or isinstance(cond, BasePermission)`) so it can be pass directly:
```
"condition": permissions.IsAuthorized
```

### PR DESCRIPTION
**Pull request by bogdandm**

### CODE REVIEW

**Comment by bogdandm** [comment]
Resolve #3

**Comment by rsinger86** [comment]
Thanks! I can definitely value in allowing regular Permissions as inputs to a statement's "condition" - it seems like it would ease reuse of condition logic across policies. Also, it would likely make it easier for existing codebases that use regular Permissions to transition to using this project. 

However, statements would no longer be JSON serializable, which wouldn't allow loading statements as easily from a data store, a feature outlined here: https://github.com/rsinger86/drf-access-policy#loading-statements-from-external-source. My other concern is that a policy's logic would no longer be encapsulated in a single file/document, as the Permission classes would be defined elsewhere.

Though, I'm coming at this from the perspective of the projects that I work on - where it's really nice for non-programmers to edit JSON in a web GUI to change authorization rules. So maybe there is a clean way to design a clean API to handle both cases: JSON serializable statements as well as more code-centric ones with direct reference to Python constructs. 

I'm certainly open to this approach, but should probably mull it over more. I'd appreciate any of your thoughts here.

**Comment by bogdandm** [comment]
OK, I understand your point of view. If you want to keep everything in JSON format the only solution I can think of would be to pass absolute import path (i.e. `"import:rest_framework.permissions.IsAuthorized"`). I don't know would be it useful or not, but it will work as compromise solution.
P.S. If I need to determine dynamic permissions through admin site I usually use default model permissions (create, update, delete and read).

**Comment by bogdandm** [comment]
Implement `"condition": "import:rest_framework.permissions.IsAuthorized"` syntax.

**Pull request closed without merging**
